services:
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_DB=CatalogDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postges_catalog:/var/lib/postgresql/data